### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by peterennis** [seanwuapps/wu-components#1]
![capture341](https://user-images.githubusercontent.com/140737/42425885-7086f42a-82d7-11e8-8058-f311c27c147d.png)
![capture340](https://user-images.githubusercontent.com/140737/42425887-75166a5c-82d7-11e8-91cf-203a835a13e0.png)

**Comment by seanwuapps** [comment]
yep, thanks for pointing it out, i actually never had a chance to set up a demo page properly, for now just ignore the link please ;P

**Comment by seanwuapps** [comment]
should be fixed now :)
